# here i import some important library 

In [1]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
import numpy as np


# loading the dataset 

In [2]:
# after uploading the dataset we extract the independent and dependent features like data and target

iris = load_iris()
X = iris.data
y = iris.target

In [3]:
# checking the shape of the dataset
X.shape, y.shape

((150, 4), (150,))

In [94]:
# Normalize the features
scaler = StandardScaler()
x= scaler.fit_transform(X)
x.shape

(150, 4)

In [6]:
from sklearn.preprocessing import OneHotEncoder
onehot=OneHotEncoder()
one_hot=onehot.fit_transform(y.reshape(-1,1)).toarray()
one_hot.shape

(150, 3)

# Spliting the data into x_train,y_train,x_test,y_test

In [8]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(X,one_hot, test_size=0.3,random_state=None)
print('Train size: {train}, Test size: {test}'.format(train=x_train.shape[0], test=x_test.shape[0]))
x_train.shape,y_train.shape,x_test.shape,y_test.shape

Train size: 105, Test size: 45


((105, 4), (105, 3), (45, 4), (45, 3))

In [9]:
# inisiallizing the weights and bias,INPUT_LAYER, OUTPUT_LAYER, HIDDEN_LAYER

In [10]:
INPUT_LENGHT = x_train.shape[1] # 784 
HIDDEN_UNITS = 4
classes=3

Win = np.random.normal(size=[INPUT_LENGHT, HIDDEN_UNITS])
bias1 = np.zeros((1, HIDDEN_UNITS))
bias2=  np.zeros((1, classes))   

print('Input Weight shape: {shape}'.format(shape=Win.shape))
print('Input bias1 shape: {shape}'.format(shape=bias1.shape))
print('Input bias2 shape: {shape}'.format(shape=bias2.shape))
print(x_train.shape[1] )

Input Weight shape: (4, 4)
Input bias1 shape: (1, 4)
Input bias2 shape: (1, 3)
4


In [12]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [13]:
# HERE I DONT USE AND ANY ACTIVATION FUNCTION IN OUTPUT LAYER 
# def softmax( x):
#         exps = np.exp(x - np.max(x, axis=1, keepdims=True))
#         return exps / np.sum(exps, axis=1, keepdims=True)

# HERE THE CALCULATING THE INPUT OF HIDDEN LAYER

In [14]:
def input_to_hidden(x):
    a = sigmoid(np.dot(x, Win)+bias1)
    return a

# Calculating the beta value 

In [17]:
X = input_to_hidden(x_train)
print(X.shape)
Xt = np.transpose(X)
print(Xt.shape)
# Wout = np.dot(np.linalg.inv(np.dot(Xt, X)), np.dot(Xt, y_train))
H_inverse = np.dot(np.linalg.inv(np.dot(Xt,X)),Xt)
beta = np.dot(H_inverse,y_train)

print('Output beta shape: {shape}'.format(shape=beta.shape))
print(Xt.shape)

(105, 4)
(4, 105)
Output beta shape: (4, 3)
(4, 105)


# output layer 

In [19]:
def predict(x):
    x = input_to_hidden(x)
    y =np.dot(x, beta)+bias2
    return y

# Model checking for prediction

In [22]:
y = predict(x_test)
print(y)

[[-8.49903935e-02  2.34494133e-01  8.50499026e-01]
 [ 1.07320550e+00 -1.57799961e-01  8.46093323e-02]
 [-5.39953700e-03  2.63059767e-01  7.42336707e-01]
 [ 1.06069542e+00 -4.68878022e-02 -1.38113583e-02]
 [ 1.42519424e-01  7.37737078e-01  1.19739023e-01]
 [-7.69079863e-04  1.45435957e-01  8.55327559e-01]
 [ 4.81932957e-02  5.87884752e-01  3.63923719e-01]
 [ 8.50305190e-01  3.00618098e-01 -1.50930899e-01]
 [-2.24113181e-02  3.89668912e-01  6.32744572e-01]
 [ 9.22619506e-01  1.01555327e-01 -2.41679085e-02]
 [ 1.09070909e-01  5.08297362e-01  3.82625017e-01]
 [ 7.32231671e-02  3.89320605e-01  5.37450050e-01]
 [ 3.62239216e-02  1.94576043e-01  7.69191838e-01]
 [ 7.46236995e-01  3.87445949e-01 -1.33688477e-01]
 [-2.57666157e-02  3.60679201e-01  6.65088699e-01]
 [ 2.59300486e-02  4.61783016e-01  5.12287029e-01]
 [ 2.74399538e-02  8.14649828e-01  1.57919290e-01]
 [ 5.56328646e-03  3.35364928e-01  6.59070589e-01]
 [ 9.20753596e-01  1.49973201e-01 -7.07277287e-02]
 [ 7.35104650e-01  4.82651251e-

In [27]:
y_test

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
from sklearn.metrics import mean_absolute_error,mean_squared_error
print(mean_absolute_error(y_test,y))



0.201574691544932


In [26]:
print(mean_squared_error(y,y_test))

0.07346936035272607
